### ISSUE TITLE
empty album

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wggallery#84]
When you create an album, even if there are no images in it yet, you can download a .zip file. This file is 4kb but it does not open. I think that you should not be able to download an album if it is empty.

**Comment by ggoffy** [comment]
fixed

**Comment by cesagonchu** [comment]
Unfortunately, the download button is still present when an album has no images yet:

![image](https://user-images.githubusercontent.com/4613970/156887894-cefa948d-01bb-462a-b28e-e2a6c3c052e8.png)


Button link:
modules/wggallery/download.php?op=album&alb_id=1

**Comment by ggoffy** [comment]
do you use a custom template set in your theme?

**Comment by cesagonchu** [comment]
I use xswatch4 :)

**Comment by ggoffy** [comment]
please use tpl files from extras/themes/xswatch4/

**Comment by cesagonchu** [comment]
I did, but the button is still there. I changed browsers, emptied the caches. I also checked yes to "Check templates for modifications?".
With the other themes, the button is removed.

**Comment by cesagonchu** [comment]
I made a mistake in sending the files. It's ok, the button is also removed with the xswatch4 theme.
